name: validate

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate-hassfest:
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: "actions/checkout@v7.0.1"
      - name: validation
        uses: home-assistant/actions/hassfest@a7c616ce81ccda50150bf1595786c71b1883fabb

  validate-hacs:
    name: HACS validation
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: "actions/checkout@v7.0.1"
      - name: validation
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"
