name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Create zip
        run: |
          cd custom_components
          zip -r ../kohler.zip kohler

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./kohler.zip
          asset_name: kohler.zip
          tag: ${{ github.ref }}
          overwrite: true
